"""State definitions for the LangGraph agent."""

from typing import Annotated, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """State schema for the Medicine Assistant agent.

    Attributes:
        messages: The conversation history with the user.
        context: Retrieved context from the RAG system.
        patient_info: Information about the current patient.
        recommendations: Medicine recommendations generated by the agent.
    """

    messages: Annotated[list[BaseMessage], add_messages]
    context: str
    patient_info: str
    recommendations: str
